name: "Deploy App."
on:
 push:
   branches: [main]
permissions:
  contents: read
jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:

     - name: Checkout repository
       uses: actions/checkout@v4

     - name: "Compress sources."
       run: |
        mkdir sources
        mv backend frontend .dockerignore docker-compose.yml sources
        ls sources
        tar -cvf sources.tar sources
     
     - name: "Install \"sshpass\"."
       run: sudo apt-get install -y sshpass

     - name: "Upload files to Droplet."
       run: sshpass -v -p ${{ secrets.DROPLET_PWD }} scp -o StrictHostKeyChecking=no sources.tar root@${{ secrets.DROPLET_IP }}:~
    
     - name: Deploy
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.DROPLET_IP }}
         username: root
         password: ${{ secrets.DROPLET_PWD }}
         script: |
           cd ~
           export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
           tar -xvf sources.tar
           rm -rf sources.tar
           mv sources mocha
           cd mocha
           docker-compose build
           docker-compose up -d
