name: "Deploy App."
on:
 push:
   branches: [main]
permissions:
  contents: read
jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:

     - name: Checkout repository
       uses: actions/checkout@v4

     - name: "Compress sources."
       run: |
        mkdir sources
        mv backend frontend .dockerignore docker-compose.yml sources
        ls sources
        echo "in sources look up"
        tar -cf sources.tar sources
        mkdir test
        mv sources.tar test
        cd test
        tar -xvf sources.tar
        echo "in test"
        ls
     
     #- name: "Install \"sshpass\"."
     #  run: sudo apt-get install -y sshpass

     #- name: "Upload files to Droplet."
     #  run: sshpass -v -p ${{ secrets.DROPLET_PWD }} scp -o StrictHostKeyChecking=no sources.tgz root@${{ secrets.DROPLET_IP }}:~
