name: "Deploy App."
on:
 push:
   branches: [main]
permissions:
  contents: read
jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:

     - name: Checkout repository
       uses: actions/checkout@v4

     - name: "Build Container."
       uses: ndeloof/install-compose-action@v0.0.1
       with:
         version: v2.1.0 # defaults to 'latest'
         legacy: true    # will also install in PATH as `docker-compose`
     - run: docker-compose build
     
     - name: "Install \"sshpass\"."
       run: sudo apt-get install -y sshpass

     - name: "Export the built images."
       run: |
        docker save -o frontend_service.tar frontend_service
        docker save -o backend_service.tar backend_service
        docker save -o db_service.tar db_service
     
     - name: "Export the built images."
       run: |
         mkdir services
         mv frontend_service.tar services
         mv backend_service.tar services
         mv db_service.tar services
         tar -cf services.tar services
         ls      

     #- name: "Upload files to Droplet."
     #  run: sshpass -v -p ${{ secrets.DROPLET_PWD }} scp -o StrictHostKeyChecking=no sources.tgz root@${{ secrets.DROPLET_IP }}:~
